encoding: utf-8

# SEO
title: JM Blog
description: JM's blog
keywords: JM, Blog
author: JM

permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# domainurl
# baseurl
domainUrl: ''
baseurl: ''

# menu
menu:
  - title: Home
    url: /
  - title: Categories
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  - title: Links
    url: /pages/links.html
  - title: Messages
    url: /pages/chat.html
  - title: About
    url: /pages/about.html

# click effect
extClickEffect: false

# Google Adsense
# _includes/ext-adsense.html
extAdsense: false

# MTA
# _includes/ext-adsense.html
extMTA: true

# Baidu
extBaidu: true

# math
extMath: false

# links
links:
  - title: APRIL Lab
    url: https://april.zju.edu.cn

    
